name: Hello 01-nif2-org-pub-reusable-repo1!
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-nif2-org-projectname-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello 01-nif2-org-pub-reusable-repo1!"
