# .github/workflows/my-reusable-workflow.yaml
name: Nif2 Pub Reusable Workflow
on:
  workflow_call:
    inputs:
      my-input:
        description: 'Input for my reusable workflow'
        required: true
        type: string

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        run: |
          echo "Hello from my reusable workflow! Input: ${{ inputs.my-input }}"